config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'plates#index'
  resources :plates

end

app/models/plate.rb
class Plate < ActiveRecord::Base
  has_many :translations, dependent: :destroy
  validates :plate_number, :presence => true, length: { maximum: 9 }
  belongs_to :user
  accepts_nested_attributes_for :translations, :reject_if => :all_blank
#  :reject_if => lambda { |a| a[:meaning].blank? }
  attr_accessor :input_rating
#  mount_uploader :asset, AssetUploader
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :plate
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  validates :first_name, presence: true
  validates :last_name, presence: true
    
  def full_name
    fullname = "#{first_name}, #{last_name}"
  end

  #only needed if not using Devise
  #has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  
  def index
    @plates = Plate.all
  end
  
  def new
    @plate = Plate.new
    @plate.translations.build
  end

#def new
#  @survey = Survey.new
#  3.times do
#    question = @survey.questions.build
#    4.times { question.answers.build }
#  end
#end

  def create
    #@plate = Plate.new(params[:plate])
    #@translation = Translation.new(plate_params[:meaning].merge(plate_id: :id, user_id: 1))
#    puts plate_params
    if plate_params[:translations_attributes]["0"]["meaning"] then vote = 1 else vote = 0 end
    @plate = Plate.new(plate_params.merge(user_id: 1, rated_count: 1, rating: :input_rating, translation_votes: vote))
#     translations_attributes: [ { plate_id: :id, user_id: 1, 
#     votes: 1 }]))
#    @plate = Plate.new(plate_params.merge(user_id: 1, rated_count: 1, rating: :input_rating, #translation_votes: vote, translations_attributes: [ { plate_id: :id }, { user_id: 1 }, 
#      { meaning: :meaning }, { votes: 1 }]))
    if @plate.save
      flash[:notice] = "Plate has been created."
      #redirect_to index
      redirect_to root_path
    else
      flash[:alert] = "Plate has not been created"
      #flash[:error] = "Failed to create post."
      #redirect_to new_post_path
      render "new"
    end
  end
  
  def show
    @plate = Plate.find(params[:id])
  end
  
  private
  
  def plate_params
    params.require(:plate).permit(:plate_number, :plate_image, :state, :input_rating,                 translations_attributes: [ :id, :meaning ])
#    params.require(:plate).permit!
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_plate
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
#  before_action :sign_in_as!(user)
#  before_action :require_signin!, except: [:show, :index]
 
  def new
    @translation = @plate.translations.build
  end
  
# def edit
#    @comment = Comment.find(comment_params)
#   @comment = @post.comments.find(params[:id])
# end
  
  def create
    @translation = @plate.translations.build(translation_params)
    @translation.user = current_user
    if @translation.save
      flash[:notice] = "Translation has been saved."
      redirect_to @plate
    else
      flash[:alert] = "Translation has not been saved."
      render "new"
    end
  end
  
  def update
    if @translation.update(translation_params)
      flash[:notice] = "Translation has been updated."
      redirect_to @plate
    else
      flash[:alert] = "Translation has not been updated."
      render "new"
    end
  end
  
#  def destroy
#  @post = Post.find(params[:post_id])
#   @comment = @post.comments.find(params[:id])
#   @comment.destroy
#   redirect_to post_path(@post)
    
    def destroy
      @translation.destroy
      flash[:notice] = "Translation has been deleted."
      redirect_to @plate

  end
  
  private
  def set_plate
    @plate = Plate.find(params[:plate_id])
  end
  
  def set_translation
#   @comment = Comment.find(params)
#   @comment = Comment.find(params[:id])
    @translation = @plate.translations.find(params[:id])
  end
  
  def translation_params
    params.require(:meaning)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
# app/helpers/form_helper.rb
module FormHelper
#  def setup_plate(plate)
#    plate.translation ||= Translation.new
#    plate
#  end
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!-- # layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "License Plate Lingo" %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>
<%= yield %>

<!-- <p class="notice"><%= notice %></p> -->
</body>
</html>

app/views/plates/_form.html.erb
<!-- app/views/plates/_form.html.erb -->
<%= form_for(@plate) do |f| %>

<% if @plate.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@plate.errors.count, "error") %>
      prohibited this plate from being saved:</h2>
    <ul>
      <% @plate.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :plate_number, "Plate Number" %>
  <%= f.text_field :plate_number %>
</div><br><br>
<div class="form-group">
  <%= f.label :plate_image, "Image File" %>
  <%= f.file_field :plate_image %>
</div><br><br>
<div class="form-group">
  <%= f.label :state, "State" %>
  <%= f.text_field :state, class: "form-control" %>
</div><br><br>
<div class="form-group">
  <%= f.label :input_rating, "Plate Rating" %>
  <%= f.select :input_rating, options_for_select(RATINGS)  %>
</div><br><br>

<h2>Translation</h2>
<!-- %= f.fields_for :translations do |ff| %-->
<%= f.fields_for :translations, @plate.translations do |ff| %>
  <div>
<!-- %= ff.label :meaning, "Translation" %-->
    <%= ff.text_field :meaning %>
  </div><br><br>
<% end %>

<%= f.submit "Save", :name => "save", class: "btn btn-default" %>

<!--%= f.submit "Save and publish", :name => "publish", class: "btn btn-default" %>
<!--%= f.submit_tag "Save and publish" %>
<!--%= f.submit_tag "Save as draft" %>
<!--%= link_to "Save as draft", draft_post_path(@post), class: "btn btn-default" %>

<% end %>

app/views/plates/new.html.erb
<h2>New Plate</h2>

<%= render 'form' %>

app/views/plates/orig.index.html.erb
<%= link_to "New Plate", new_plate_path %>

<h2>Plates</h2>
<ul>
  <% @plates.each do |plate| %>
  <li><%= link_to plate.plate_number, plate %></li>
<% end %>
</ul>

 <td><a id="platenumber1" target="_top" href="">KAHPERD</a></td>

<tr>
                    <td><a id="platenumber2" target="_top" href="">WEDEMAN</a><br>
                    </td>
                    <td><img alt="plate image" src="images/WEDEMANplate.gif"><br>
                    </td>
                    <td>Dave Ryan<br>
                    </td>
                    <td>name<br>
                    </td>
                  </tr>
                  <tr>
                    <td><br>
                    </td>
                    <td><br>
                    </td>
                    <td><br>
                    </td>
                    <td><br>
                    </td>
                  </tr>

                    <td>Dave Ryan</td>

 <td>Kentucky Alliance for Health, Physical Education, Recreation and Dance</td>

<td><%= if plate.translations.count > 0
                      plate.translations.first.meaning %>
                    <% end %></td>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>